# docker-compose.yml

version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    volumes:
      - ex1-db:/var/lib/postgresql/data

  ex1:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_MIGRATION_TIMEOUT: 10000
      NODE_ENV: production
    depends_on:
      - postgres  
    ports:
      - 3000:3000
    command: sh -c "npm run-script migrate && npm run-script pm2"            
volumes:
  ex1-db: